### ISSUE TITLE
invalid key on private_command

### ISSUE THREAD

**Issue by kenyhenry** [voidloop/krakenapi#12]
key/secret pair is use only on private_command call. 
When implementing AddOrder command unexpected error "EAPI:Invalid key"
please contact me for more informations

**Comment by voidloop** [comment]
I'm sorry @kenyhenry, but I'm not sure I understand what you mean.
Could you give me an example? 
I have created a sample folder for you in the project. 
Does private_method.cpp solve your problem?

**Comment by kenyhenry** [comment]
ok i'll take a look andl come back to you. Thanx you for your reply

**Comment by kenyhenry** [comment]
ok it's that simple ?! i was trying to create the AddOrder method in the KClient class after seeing some TODO in comments-> [personal KClient class](https://github.com/kenyhenry/krakenapi/blob/master/kraken/kclient.cpp) 
contact me if you see anything wrong, sorry for the code quality it's a mess, i will clean up after,also i am think of a LOGGER class too, but still in progress.

**Comment by kenyhenry** [comment]
work good
