### ISSUE TITLE
xstring problem while compiling the krt.cpp

### ISSUE THREAD

**Issue by Cchrisking** [voidloop/krakenapi#8]
krt.cpp
krt.cpp(116): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2389): warning C4244: 'argument': conversion from 'const wchar_t' to 'const _Elem', possible loss of data
        with
        [
            _Elem=char
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2400): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<const wchar_t*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
        with
        [
            _Iter=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2400): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<const wchar_t*>(_Iter,const _Iter,std::input_iterator_tag)' being compiled
        with
        [
            _Iter=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2380): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<const wchar_t*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Iter=const wchar_t *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xstring(2380): note: see reference to function template instantiation 'void std::basic_string<char,std::char_traits<char>,std::allocator<char>>::_Construct<const wchar_t*>(const _Iter,const _Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Iter=const wchar_t *
        ]
H:\tradingbot\tradingbot3\kraken\../libjson/libjson.h(233): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)' being compiled
        with
        [
            _Elem=wchar_t,
            _Iter=std::_String_const_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
            _Alloc=std::allocator<char>
        ]
H:\tradingbot\tradingbot3\kraken\../libjson/libjson.h(233): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Elem>>>,0>(_Iter,_Iter,const _Alloc &)' being compiled
        with
        [
            _Elem=wchar_t,
            _Iter=std::_String_const_iterator<std::_String_val<std::_Simple_types<wchar_t>>>,
            _Alloc=std::allocator<char>
        ]
Microsoft (R) Incremental Linker Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:krt.exe
krt.obj
krt.obj : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl Kraken::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,struct Kraken::KTrade const &)" (??6Kraken@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAV12@ABUKTrade@0@@Z) referenced in function _main
krt.obj : error LNK2019: unresolved external symbol "public: __thiscall Kraken::KClient::KClient(void)" (??0KClient@Kraken@@QAE@XZ) referenced in function _main
krt.obj : error LNK2019: unresolved external symbol "public: __thiscall Kraken::KClient::~KClient(void)" (??1KClient@Kraken@@QAE@XZ) referenced in function _main
krt.obj : error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall Kraken::KClient::trades(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::vector<struct Kraken::KTrade,class std::allocator<struct Kraken::KTrade> > &)" (?trades@KClient@Kraken@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@0AAV?$vector@UKTrade@Kraken@@V?$allocator@UKTrade@Kraken@@@std@@@4@@Z) referenced in function _main
krt.obj : error LNK2019: unresolved external symbol "void __cdecl Kraken::initialize(void)" (?initialize@Kraken@@YAXXZ) referenced in function _main
krt.obj : error LNK2019: unresolved external symbol "void __cdecl Kraken::terminate(void)" (?terminate@Kraken@@YAXXZ) referenced in function _main

**Comment by voidloop** [comment]
Hi, do you still have this problem?
